---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    name: voting-app-service
    author: nana
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis-deployment
...