---
apiVersion: apps/v1
kind: DeploymentPod
metadata:
  name: result-app-deployment
  labels:
    name: result-app-pod
    author: nana
spec:
  replicas: 2
  selector:
    matchLabels:
      name: result-app-deployment
  template:
    metadata:
      name: result-app-deployment
    spec:
      containers:
        - name: result-app
          image: dockersamples/examplevotingapp_result
...