---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    name: voting-app-service
    author: nana
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort:
  selector:
    name: voting-app-deployment
...